apiVersion: v1
kind: Pod
metadata:
  name: storage
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
          # name must match the volume name below
        - name: redis-persistent-storage
          # mount path within the container
          mountPath: /data/redis
  volumes:
    - name: redis-persistent-storage
      emptyDir: {}
